var age = 21;
var month = 05;
var days = -2;
var hours = 57.6;
var first = "Hello World!";
var apol = "I'm so sorry!";
var lost ="Where am I?";
var man = true;
var likejs = true;
var whoknows = undefined;
console.log("How old are you?", age);
console.log("What month were you born in?", month);
console.log("How many days are you behind in your goals?", days);
console.log("How many hours do you waste a day?", hours);
console.log("I've just been born!", first);
console.log("How could you have done this?", apol);
console.log("How did you get here?", lost);
console.log("You are a man.", man);
console.log("Do you like JavaScript?", likejs);
console.log("What is this variable?", whoknows);
